### PR TITLE
fix:#7 added new styles to heading✌️

### PR DESCRIPTION
**Pull request by Pritam0077**
I have added some new styles in the heading

### CODE REVIEW

**Comment by abhishek622** [comment]
It is good but try to change font as well and give it some funky look. You can look for different fonts in [google fonts](https://fonts.google.com/)

**Comment by Pritam0077** [comment]
ok

**Comment by Pritam0077** [comment]
I have added the new styles

**Comment by abhishek622** [comment]
I have merged one pull request so first, you need to do `git pull` to update your local repo and then make changes and create a pull request.

**Comment by Pritam0077** [comment]
my local repo is already updated and i made the necessary changes,do i have to push the commits again ?

**Pull request merged**
